import {
  Bot,
  Boxes,
  BrainCircuit,
  Calculator,
  Code2,
  Database,
  Gauge,
  LayoutDashboard,
  Layers,
  Library,
  Navigation,
  Radar,
  Rocket,
  Search,
  Server,
  Terminal,
  Wallet,
  Wrench,
} from 'lucide-react';

// Data files reference icons by name so they stay plain, serializable objects.
export const icons = {
  bot: Bot,
  boxes: Boxes,
  brain: BrainCircuit,
  calculator: Calculator,
  code: Code2,
  database: Database,
  gauge: Gauge,
  layers: Layers,
  layout: LayoutDashboard,
  library: Library,
  navigation: Navigation,
  radar: Radar,
  rocket: Rocket,
  search: Search,
  server: Server,
  terminal: Terminal,
  wallet: Wallet,
  wrench: Wrench,
};
